//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BILL()
        {
            this.CARTs = new HashSet<CART>();
        }
    
        public string BILL_ID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string CUST_NAME { get; set; }
        public string CUST_ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<double> DELIVERY { get; set; }
        public string PAYMENT_ID { get; set; }
        public string COUPON_ID { get; set; }
    
        public virtual COUPON COUPON { get; set; }
        public virtual PAYMENT_METHODD PAYMENT_METHODD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART> CARTs { get; set; }
    }
}
