//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOG
    {
        public string BLOG_ID { get; set; }
        public string CONTENT { get; set; }
        public string IMG_ID { get; set; }
    
        public virtual IMG IMG { get; set; }
    }
}
