//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public string MESS_ID { get; set; }
        public string NAME_SENDER { get; set; }
        public string EMAIL { get; set; }
        public string SUBJECT { get; set; }
        public string MESSAGE_CONT { get; set; }
    }
}
